---
- name: Docker installation
  hosts: all
  become: true
  tasks:
    - name: Add Docker CE repo
      ansible.builtin.dnf:
        name: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
        disable_gpg_check: false
    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-ce-rootless-extras
        state: present
        update_cache: true
    - name: Start and enable docker service
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started
