---
- name: Uninstall nginx playbook
  hosts: all
  become: true

  tasks:
   - name: Nginx serivce stop
     ansible.builtin.service:
      name: nginx
      state: stopped
   - name: Nginx installation
     ansible.builtin.yum:
      name: nginx
      state: absent
